// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:93d3103c-de8c-47ba-9efb-bf33c2e99c0c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_m3FF5gTbn",
    "aws_user_pools_web_client_id": "5ik609mbbb1pcek5re23tpbjgh",
    "oauth": {}
};


export default awsmobile;
